# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=80)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(null=True, blank=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(unique=True, max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(null=True, blank=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, serialize=False, primary_key=True)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mix2',
            fields=[
                ('index_u', models.BigIntegerField(null=True, blank=True)),
                ('follow_request_sent_u', models.NullBooleanField()),
                ('has_extended_profile_u', models.NullBooleanField()),
                ('profile_use_background_image_u', models.NullBooleanField()),
                ('idd_u', models.BigIntegerField(null=True, blank=True)),
                ('default_profile_u', models.NullBooleanField()),
                ('verified_u', models.NullBooleanField()),
                ('profile_text_color_u', models.TextField(null=True, blank=True)),
                ('profile_image_url_https_u', models.TextField(null=True, blank=True)),
                ('profile_sidebar_fill_color_u', models.TextField(null=True, blank=True)),
                ('is_translator_u', models.NullBooleanField()),
                ('geo_enabled_u', models.NullBooleanField()),
                ('followers_count_u', models.BigIntegerField(null=True, blank=True)),
                ('profile_sidebar_border_color_u', models.TextField(null=True, blank=True)),
                ('location_u', models.TextField(null=True, blank=True)),
                ('default_profile_image_u', models.NullBooleanField()),
                ('id_str_u', models.TextField(null=True, blank=True)),
                ('is_translation_enabled_u', models.NullBooleanField()),
                ('utc_offset_u', models.FloatField(null=True, blank=True)),
                ('statuses_count_u', models.BigIntegerField(null=True, blank=True)),
                ('description_u', models.TextField(null=True, blank=True)),
                ('friends_count_u', models.BigIntegerField(null=True, blank=True)),
                ('profile_link_color_u', models.TextField(null=True, blank=True)),
                ('profile_image_url_u', models.TextField(null=True, blank=True)),
                ('notifications_u', models.NullBooleanField()),
                ('profile_background_image_url_https_u', models.TextField(null=True, blank=True)),
                ('profile_background_color_u', models.TextField(null=True, blank=True)),
                ('profile_background_image_url_u', models.TextField(null=True, blank=True)),
                ('name_u', models.TextField(null=True, blank=True)),
                ('lang_u', models.TextField(null=True, blank=True)),
                ('profile_background_tile_u', models.NullBooleanField()),
                ('favourites_count_u', models.BigIntegerField(null=True, blank=True)),
                ('screen_name_u', models.TextField(null=True, blank=True)),
                ('url_u', models.TextField(null=True, blank=True)),
                ('created_at_u', models.TextField(null=True, blank=True)),
                ('contributors_enabled_u', models.NullBooleanField()),
                ('time_zone_u', models.TextField(null=True, blank=True)),
                ('protected_u', models.NullBooleanField()),
                ('translator_type_u', models.TextField(null=True, blank=True)),
                ('following_u', models.NullBooleanField()),
                ('listed_count_u', models.BigIntegerField(null=True, blank=True)),
                ('profile_banner_url_u', models.TextField(null=True, blank=True)),
                ('id_u', models.BigIntegerField(null=True, blank=True)),
                ('index', models.FloatField(null=True, blank=True)),
                ('unnamed_0', models.TextField(null=True, db_column='Unnamed: 0', blank=True)),
                ('contributors', models.TextField(null=True, blank=True)),
                ('truncated', models.NullBooleanField()),
                ('text', models.TextField(null=True, blank=True)),
                ('is_quote_status', models.TextField(null=True, blank=True)),
                ('in_reply_to_status_id', models.TextField(null=True, blank=True)),
                ('idd', models.FloatField(null=True, blank=True)),
                ('favorite_count', models.FloatField(null=True, blank=True)),
                ('source', models.TextField(null=True, blank=True)),
                ('retweeted', models.TextField(null=True, blank=True)),
                ('in_reply_to_screen_name', models.TextField(null=True, blank=True)),
                ('in_reply_to_user_id', models.TextField(null=True, blank=True)),
                ('retweet_count', models.FloatField(null=True, blank=True)),
                ('id_str', models.TextField(null=True, blank=True)),
                ('favorited', models.TextField(null=True, blank=True)),
                ('in_reply_to_user_id_str', models.FloatField(null=True, blank=True)),
                ('lang', models.TextField(null=True, blank=True)),
                ('created_at', models.TextField(null=True, blank=True)),
                ('in_reply_to_status_id_str', models.FloatField(null=True, blank=True)),
                ('id_twit', models.TextField(null=True, blank=True)),
                ('media_url', models.TextField(null=True, blank=True)),
                ('id', models.FloatField(serialize=False, primary_key=True)),
                ('col', models.DateTimeField(null=True, blank=True)),
                ('country_league', models.TextField(null=True, db_column='Country_league', blank=True)),
                ('league_field', models.TextField(null=True, db_column='League ', blank=True)),
                ('country', models.TextField(null=True, blank=True)),
                ('nom', models.TextField(null=True, blank=True)),
                ('club', models.TextField(null=True, blank=True)),
                ('t_id', models.BigIntegerField(null=True, blank=True)),
                ('last_tw', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'Mix2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('level_0', models.BigIntegerField(null=True, blank=True)),
                ('index', models.BigIntegerField(null=True, blank=True)),
                ('follow_request_sent', models.NullBooleanField()),
                ('has_extended_profile', models.NullBooleanField()),
                ('profile_use_background_image', models.NullBooleanField()),
                ('idd', models.BigIntegerField(null=True, blank=True)),
                ('default_profile', models.NullBooleanField()),
                ('verified', models.NullBooleanField()),
                ('profile_text_color', models.TextField(null=True, blank=True)),
                ('profile_image_url_https', models.TextField(null=True, blank=True)),
                ('profile_sidebar_fill_color', models.TextField(null=True, blank=True)),
                ('is_translator', models.NullBooleanField()),
                ('geo_enabled', models.NullBooleanField()),
                ('followers_count', models.BigIntegerField(null=True, blank=True)),
                ('profile_sidebar_border_color', models.TextField(null=True, blank=True)),
                ('location', models.TextField(null=True, blank=True)),
                ('default_profile_image', models.NullBooleanField()),
                ('id_str', models.TextField(null=True, blank=True)),
                ('is_translation_enabled', models.NullBooleanField()),
                ('utc_offset', models.FloatField(null=True, blank=True)),
                ('statuses_count', models.BigIntegerField(null=True, blank=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('friends_count', models.BigIntegerField(null=True, blank=True)),
                ('profile_link_color', models.TextField(null=True, blank=True)),
                ('profile_image_url', models.TextField(null=True, blank=True)),
                ('notifications', models.NullBooleanField()),
                ('profile_background_image_url_https', models.TextField(null=True, blank=True)),
                ('profile_background_color', models.TextField(null=True, blank=True)),
                ('profile_background_image_url', models.TextField(null=True, blank=True)),
                ('name', models.TextField(null=True, blank=True)),
                ('lang', models.TextField(null=True, blank=True)),
                ('profile_background_tile', models.NullBooleanField()),
                ('favourites_count', models.BigIntegerField(null=True, blank=True)),
                ('screen_name', models.TextField(null=True, blank=True)),
                ('url', models.TextField(null=True, blank=True)),
                ('created_at', models.TextField(null=True, blank=True)),
                ('contributors_enabled', models.NullBooleanField()),
                ('time_zone', models.TextField(null=True, blank=True)),
                ('protected', models.NullBooleanField()),
                ('translator_type', models.TextField(null=True, blank=True)),
                ('following', models.NullBooleanField()),
                ('listed_count', models.BigIntegerField(null=True, blank=True)),
                ('profile_banner_url', models.TextField(null=True, blank=True)),
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('country_league', models.TextField(null=True, db_column='Country_league', blank=True)),
                ('league_field', models.TextField(null=True, db_column='League ', blank=True)),
                ('country', models.TextField(null=True, blank=True)),
                ('nom', models.TextField(null=True, blank=True)),
                ('club', models.TextField(null=True, blank=True)),
                ('entraineur', models.FloatField(null=True, blank=True)),
                ('t_id', models.FloatField(null=True, blank=True)),
                ('last_tw', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'REF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefClub',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('index', models.BigIntegerField(null=True, blank=True)),
                ('club', models.TextField(null=True, db_column='Club', blank=True)),
                ('real_club', models.TextField(null=True, db_column='Real_club', blank=True)),
                ('league', models.TextField(null=True, db_column='League', blank=True)),
                ('country_league', models.TextField(null=True, db_column='Country_league', blank=True)),
            ],
            options={
                'db_table': 'ref_club',
                'managed': False,
            },
        ),
    ]
